### ISSUE TITLE
Something missing

### ISSUE THREAD

**Issue by vkuehn** [KleinerKobold/python_dockerized#2]
Hi,

as I am new to docker thanks for the repo !

Is it possible that there is something missing ?

requierements.txt has nothing
pyproject.toml has dependecis for 3.10 where the Dockerfile is pulling 3.11

?

**Comment by KleinerKobold** [comment]
In the requirements.txt you can add your own dependencies. 
It's just a skeleton. But in python you can use toml files to install dependencies or the requirements with pip. My project does both for demonstration.

Perhaps the toml has the wrong version, I should change that. (My local python was 3.10, but the docker was able to install the newer one)

Thank you

**Comment by vkuehn** [comment]
thanks for the explenation.

Should be not of an issue anymore
